input: .
output: .retype
url: fmhy.pages.dev
branding:
  logo: /static/fmhy.ico
  logoDark: /static/fmhy.ico
  title: FMHY
favicon: /static/favicon.ico

links: # top bar
  - text: Chat
    link: https://fmhy.divolt.xyz/
    icon: comment
  - text: Search
    link: https://fmhy-search.streamlit.app/
    icon: search
  - text: Reddit
    link: https://www.reddit.com/r/FREEMEDIAHECKYEAH/
    icon: https://www.redditstatic.com/desktop2x/img/favicon/favicon-32x32.png
  - text: Github
    link: https://github.com/fmhy
    icon: mark-github

footer:
  copyright: ""
meta:
  title: " | FreeMediaHeckYeah"
